services:
  app:
    build: 
      context: .
      dockerfile: Dockerfile.prod
      args:
        - REACT_APP_NAME=Shortyshorty-prod
        - REACT_APP_TITLE=Shorty-prod
    ports:  
      - "8080:80"