services:
  frontend:
    container_name: app
    build:
      context: .
      target: dev-envs
    ports:
      - "80:3000"
      - "3000:3000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

